FROM openjdk:17-jdk-alpine
MAINTAINER Gruppe43
COPY build/libs/MoneyManager-0.0.1-SNAPSHOT.jar MoneyManager-0.0.1-SNAPSHOT.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar","/MoneyManager-0.0.1-SNAPSHOT.jar"]