version: '3.1'
services:
  postgresapp:
    image: 'postgres:15.2-alpine'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MoneyData
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  moneymanager:
    container_name: moneymanager
    build:
      context: docker-moneymanager
      dockerfile: Dockerfile
    image: moneymanager:latest
    ports:
      - "9000:9000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}