version: '3.1'
services:
  moneymanager:
    container_name: moneymanager
    build:
      context: docker-moneymanager
      dockerfile: Dockerfile
    image: moneymanager:latest
    ports:
      - 9000