version: '3.1'
services:
  database:
    image: 'postgres:15.2-alpine'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=MoneyData"
    ports:
      - "5432:5432"
    expose:
      - "5432"
      #moneymanager:
      # container_name: moneymanager
      #build:
      # context: docker-moneymanager
      # dockerfile: Dockerfile
      #image: moneymanager:latest
      #ports:
      # - "9000:9000"
      #environment:
      # - CLIENT_ID=${CLIENT_ID}
      #- CLIENT_SECRET=${CLIENT_SECRET}