spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
